### ISSUE TITLE
Mapping Tool, invalid input path, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#45]
**Test ID:** MAP-003    
**Test name:** Run Mapping Tool with invalid input and valid mapping file      
**Precondition:** -     
**Steps:**      
1. Open a command line.     
2. Run Mapping Tool with an invalid input and valid mapping file, for example:      
java -jar codemetropolis-toolchain-mapping-1.3.jar -i Modules\Java3Projectssss.graph -o Modules\mappingToPlacing.xml -m mapping.xml      
**Expected Result:** Error: File Modules\Java333Projects.graph not found!   

**Result:**
Mapping: Reading map file...
Mapping: Reading map file done.
Mapping: Reading graph file...
Exception in thread "main" columbus.ColumbusException: File Modules\Java3Projectssss.graph not found!
        at graphlib.Graph.loadBinary(Graph.java:393)
        at codemetropolis.toolchain.mapping.control.MappingController.createBuil
dablesFromGraph(MappingController.java:48)
        at codemetropolis.toolchain.mapping.MappingExecutor.execute(MappingExecu
tor.java:34)
        at codemetropolis.toolchain.mapping.Main.main(Main.java:32)

**Comment by brita-sed** [comment]
I got a user friendly message now instead of exception: Error: No CDF file was found on the given path.
