### ISSUE TITLE
Mapping Tool, invalid mapping file path, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#46]
**Test ID:** MAP-002
**Test name:**	Run Mapping Tool with valid input and invalid mapping file
**Precondition:**	-
**Steps:**
1. Open a command line. 
2. Run Mapping Tool with a valid input and invalid mapping file, for example: 
java -jar codemetropolis-toolchain-mapping-1.3.jar -i Modules\Java3Projects.graph -m mapping123.xml
**Expected Result:**	Mapping tool will display an error message: The system couldn't find the given mapping file. 

**Result:**
Mapping: Reading map file...
codemetropolis.toolchain.mapping.exceptions.MappingReaderException: java.io.FileNotFoundException: c:\work\CodeMetropolis\mapping123.xml (A rendszer nem találja a megadott fájlt)
        at codemetropolis.toolchain.mapping.model.Mapping.readFromXML(Mapping.ja
va:54)
        at codemetropolis.toolchain.mapping.MappingExecutor.execute(MappingExecu
tor.java:22)
        at codemetropolis.toolchain.mapping.Main.main(Main.java:32)
Caused by: java.io.FileNotFoundException: c:\work\CodeMetropolis\mapping123.xml
(A rendszer nem találja a megadott fájlt)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrent
Entity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineD
ocVersion(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(U
nknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown So
urce)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unk
nown Source)
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
        at codemetropolis.toolchain.mapping.model.Mapping.readFromXML(Mapping.ja
va:49)
        ... 2 more

**Comment by brita-sed** [comment]
I got a user friendly message now: Error: No mapping file was found on the given path.
