### ISSUE TITLE
Mapping Tool, invalid output file path, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#47]
**Test ID:** MAP-006
**Test name:** Run Mapping Tool with valid input and mapping file, and with invalid output
**Precondition:** -
**Steps:** 
1. Open a command line. 
2. Run Mapping Tool with a valid input, valid mapping file and with invalid -o parameter, for example: 
java -jar codemetropolis-toolchain-mapping-1.3.jar -i Modules\Java3Projects.graph -m mapping.xml -o \Mapping_output.xml"
**Expected Result:** The Mapping tool will display an error message: g:\Mapping_output.xml cannot found! 

**Result:**
Mapping: Reading map file...
Mapping: Reading map file done.
Mapping: Reading graph file...
Mapping: Reading graph file done.
Mapping: Linking metrics to buildables...
Mapping: Linking metrics to buildables done.
Mapping: Generating input for placing...
codemetropolis.toolchain.commons.cmxml.exceptions.CmxmlWriterException: javax.xml.transform.TransformerException: java.io.FileNotFoundException: g:\Modules\mappingToPlacing.xml (A rendszer nem találja a megadott elérési utat)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:218)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:175)
        at codemetropolis.toolchain.mapping.MappingExecutor.execute(MappingExecu
tor.java:43)
        at codemetropolis.toolchain.mapping.Main.main(Main.java:32)
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundExcepti
on: g:\Modules\mappingToPlacing.xml (A rendszer nem találja a megadott elérési u
tat)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutpu
tHandler(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transfor
m(Unknown Source)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:216)
        ... 3 more
Caused by: java.io.FileNotFoundException: g:\Modules\mappingToPlacing.xml (A ren
dszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        ... 6 more

**Comment by brita-sed** [comment]
I got a user friendly message now: Error: An error has occurred while writing the output file. For more information please check the log file.
