### ISSUE TITLE
Placing Tool, invalid output file path, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#48]
**Test ID:** PLA-005
**Test name:** Run Placing Tool with valid input file, and with invalid output
**Precondition:** Input XML file with Mapping tool has been generated. 
**Steps:** 
1. Open a command line. 
2. Run Placing Tool with a valid input and with invalid -o parameter, for example: 
java -jar codemetropolis-toolchain-placing-1.3.jar -i Modules\Mapping_output.xml -o g:\Modules\Placing_output.xml
**Expected Result:** The Placing tool will display an error message: output path cannot found! 
	
**Result:**
Placing: Reading input file...
Placing: Reading input file done.
Placing: Calculating building sizes and positions...
Placing: Calculating building sizes and positions done.
Placing: Generating input for rendering...
codemetropolis.toolchain.commons.cmxml.exceptions.CmxmlWriterException: javax.xml.transform.TransformerException: java.io.FileNotFoundException: g:\Modules\placingToRendering.xml (A rendszer nem találja a megadott elérési utat)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:218)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:175)
        at codemetropolis.toolchain.placing.PlacingExecutor.execute(PlacingExecu
tor.java:58)
        at codemetropolis.toolchain.placing.Main.main(Main.java:32)
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundExcepti
on: g:\Modules\placingToRendering.xml (A rendszer nem találja a megadott elérési
 utat)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutpu
tHandler(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transfor
m(Unknown Source)
        at codemetropolis.toolchain.commons.cmxml.BuildableTree.writeToFile(Buil
dableTree.java:216)
        ... 3 more
Caused by: java.io.FileNotFoundException: g:\Modules\placingToRendering.xml (A r
endszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        ... 6 more
Placing: Generating input for rendering done.

**Comment by brita-sed** [comment]
I got a user friendly message: 
Error: An error has occurred while writing the output file. For more information please check the log file..
