### ISSUE TITLE
Placing Tool, invalid layout parameter, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#49]
**Test ID:** PLA-007
**Test name:** Run Placing Tool with valid input and with invalid layout value. 
**Precondition:** Input XML file with Mapping tool has been generated. 
**Steps:**
1. Open a command line. 
2. Run Placing Tool with a valid input and with invalid layout value, for example: 
java -jar codemetropolis-toolchain-placing-1.3.jar -i Modules\Mapping_output.xml -l teszt
**Expected Result:** The Placing tool will display an error message: wrong layout parameter! 

**Result:**
Placing: Reading input file...
Placing: Reading input file done.
Placing: Calculating building sizes and positions...
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant
codemetropolis.toolchain.placing.layout.LayoutAlgorithm.TESZT
        at java.lang.Enum.valueOf(Unknown Source)
        at codemetropolis.toolchain.placing.layout.LayoutAlgorithm.valueOf(Layou
tAlgorithm.java:3)
        at codemetropolis.toolchain.placing.layout.Layout.parse(Layout.java:16)
        at codemetropolis.toolchain.placing.PlacingExecutor.execute(PlacingExecu
tor.java:46)
        at codemetropolis.toolchain.placing.Main.main(Main.java:32)

**Comment by brita-sed** [comment]
I got an exception again: 
Placing: Reading input file...
Placing: Reading input file done.
Placing: Calculating building sizes and positions...
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant
codemetropolis.toolchain.placing.layout.LayoutAlgorithm.TESZT
        at java.lang.Enum.valueOf(Unknown Source)
        at codemetropolis.toolchain.placing.layout.LayoutAlgorithm.valueOf(LayoutAlgorithm.java:3)
        at codemetropolis.toolchain.placing.layout.Layout.parse(Layout.java:16)
        at codemetropolis.toolchain.placing.PlacingExecutor.execute(PlacingExecutor.java:49)
        at codemetropolis.toolchain.placing.Main.main(Main.java:36)

**Comment by brita-sed** [comment]
[Eclipse_color_theme.zip](https://github.com/geryxyz/CodeMetropolis/files/147978/Eclipse_color_theme.zip)

**Comment by brita-sed** [comment]
I got a correct, user friendly message now: 
Error: Layout with the given identifier does not exist.
