### ISSUE TITLE
Rendering Tool, invalid world path, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#50]
**Test**: ID	REN-003
**Test name**: Run Rendering Tool with valid input file and invalid world path. 
**Precondition**: Input XML file with Placing tool has been generated. 
**Steps**:
1. Open a command line. 
2. Run Rendering Tool with a valid input file and an invalid world path, for example: 
java -jar codemetropolis-toolchain-rendering-1.3.jar -i \Modules\Placing_output.xml -w g:\Modules\deletable
**Expected Result**: The program will display an error message: The given path of world cannot found! 

**Result:**
java.io.FileNotFoundException: g:\Modules\deletable\level.dat (A rendszer nem ta
lálja a megadott elérési utat)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at codemetropolis.blockmodifier.ext.LevelFile.<init>(LevelFile.java:15)
        at codemetropolis.blockmodifier.Level.<init>(Level.java:17)
        at codemetropolis.blockmodifier.World.<init>(World.java:26)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldB
uilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(Renderin
gExecutor.java:61)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:32)
java.io.FileNotFoundException: g:\Modules\deletable\level.dat (A rendszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at codemetropolis.blockmodifier.ext.LevelFile.getLevelDataOutputStream(L
evelFile.java:34)
        at codemetropolis.blockmodifier.Level.writeToFile(Level.java:74)
        at codemetropolis.blockmodifier.World.<init>(World.java:27)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldB
uilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(Renderin
gExecutor.java:61)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:32)
Exception in thread "main" java.lang.NullPointerException
        at java.io.DataOutputStream.writeByte(Unknown Source)
        at codemetropolis.blockmodifier.ext.NBTTag.writeTo(NBTTag.java:407)
        at codemetropolis.blockmodifier.Level.writeToFile(Level.java:74)
        at codemetropolis.blockmodifier.World.<init>(World.java:27)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldB
uilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(Renderin
gExecutor.java:61)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:32)

**Comment by brita-sed** [comment]
I got a long exception again:
java.io.FileNotFoundException: g:\HelloWorld\HelloWorld\level.dat (A rendszer nem találja a megadott elérési utat)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at codemetropolis.blockmodifier.ext.LevelFile.<init>(LevelFile.java:15)
        at codemetropolis.blockmodifier.Level.<init>(Level.java:17)
        at codemetropolis.blockmodifier.World.<init>(World.java:26)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldBuilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(RenderingExecutor.java:65)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:36)
java.io.FileNotFoundException: g:\HelloWorld\HelloWorld\level.dat (A rendszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at codemetropolis.blockmodifier.ext.LevelFile.getLevelDataOutputStream(LevelFile.java:34)
        at codemetropolis.blockmodifier.Level.writeToFile(Level.java:74)
        at codemetropolis.blockmodifier.World.<init>(World.java:27)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldBuilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(RenderingExecutor.java:65)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:36)
Exception in thread "main" java.lang.NullPointerException
        at java.io.DataOutputStream.writeByte(Unknown Source)
        at codemetropolis.blockmodifier.ext.NBTTag.writeTo(NBTTag.java:407)
        at codemetropolis.blockmodifier.Level.writeToFile(Level.java:74)
        at codemetropolis.blockmodifier.World.<init>(World.java:27)
        at codemetropolis.toolchain.rendering.control.WorldBuilder.<init>(WorldBuilder.java:37)
        at codemetropolis.toolchain.rendering.RenderingExecutor.execute(RenderingExecutor.java:65)
        at codemetropolis.toolchain.rendering.Main.main(Main.java:36)

**Comment by blip24** [comment]
note: Occurs only when the drive in the path does not exist (otherwise the missing folder hierarchy is created). This is an error in the world builder API and will be fixed later.

**Comment by Tejes** [comment]
I'll take this.
