### ISSUE TITLE
CDF Converter requires output as a necessary parameter

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#61]
While Converter will return with an exception, if the user don't give the output (-o) parameter, the other tools like Mapping or Placing tool generates a default XML file if output parameter is missing. 

Example: 

c:\work\CodeMetropolis\BinForTest>java -jar converter.jar -i JavaModules\Java3Projects.graph
Converter: Converting input to CDF format...
Converter: Converting input to CDF format done.
Converter: Printing CDF document...
codemetropolis.toolchain.commons.cdf.exceptions.CdfWriterException: java.lang.NullPointerException
        at codemetropolis.toolchain.commons.cdf.CdfTree.writeToFile(CdfTree.java:91)
        at codemetropolis.toolchain.converter.ConverterExecutor.execute(ConverterExecutor.java:24)
        at codemetropolis.toolchain.converter.Main.main(Main.java:34)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at codemetropolis.toolchain.commons.cdf.CdfTree.writeToFile(CdfTree.java:86)
        ... 2 more

**Comment by brita-sed** [comment]
The application works fine when output parameter is missing, it generates a default converterToMapping.xml to the directory of toolchain.
