### ISSUE TITLE
Converter tool, invalid input file, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#67]
**Test ID:** CON-002
**Test name:** Run Converter Tool with invalid input file
**Precondition:**	Input graph file is available. 
**Steps**: 
1. Open a command line. 
2. Run Converter Tool with an invalid input file, for example: java -jar converter.jar -i g:\Modules\Modules.graph"
**Expected Result:**Converter tool will display an error message: Error: The given input graph does not exits.

**Result:** 
Converter: Converting input to CDF format...
Exception in thread "main" columbus.ColumbusException: File h:\JavaModules\Java3
Projects.graph not found!
        at graphlib.Graph.loadBinary(Graph.java:393)
        at codemetropolis.toolchain.converter.control.GraphConverter.createElements(GraphConverter.java:34)
        at codemetropolis.toolchain.converter.ConverterExecutor.execute(ConverterExecutor.java:19)
        at codemetropolis.toolchain.converter.Main.main(Main.java:34)

**Comment by brita-sed** [comment]
I got a user friendly message: Error: An error has occurred while converting to CDF  format. For more information please check the log file.
