### ISSUE TITLE
Converter tool, invalid output file, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#68]
**Test ID:** CON-005
**Test name:** Run Converter Tool with valid input file, and with invalid output
**Precondition:** Input graph file is available. 
**Steps:**
1. Open a command line. 
2. Run Converter Tool with a valid input and with invalid -o parameter, for example: 
java -jar converter.jar -i Modules\Modules.graph -o g:\Modules\Converter_output.xml
**Expected Result:** The Converter tool will display an error message: output path cannot found!

**Result:**
Converter: Converting input to CDF format...
Exception in thread "main" columbus.ColumbusException: File \JavaModules\Java3Pr
ojects.graph not found!
        at graphlib.Graph.loadBinary(Graph.java:393)
        at codemetropolis.toolchain.converter.control.GraphConverter.createEleme
nts(GraphConverter.java:34)
        at codemetropolis.toolchain.converter.ConverterExecutor.execute(Converte
rExecutor.java:19)
        at codemetropolis.toolchain.converter.Main.main(Main.java:34)

c:\work\CodeMetropolis\BinForTest>java -jar converter.jar -i JavaModules\Java3Pr
ojects.graph -o g:\JavaModules\converterOutput.xml
Converter: Converting input to CDF format...
Converter: Converting input to CDF format done.
Converter: Printing CDF document...
codemetropolis.toolchain.commons.cdf.exceptions.CdfWriterException: javax.xml.transform.TransformerException: java.io.FileNotFoundException: g:\JavaModules\converterOutput.xml (A rendszer nem találja a megadott elérési utat)
        at codemetropolis.toolchain.commons.cdf.CdfTree.writeToFile(CdfTree.java:91)
        at codemetropolis.toolchain.converter.ConverterExecutor.execute(ConverterExecutor.java:24)
        at codemetropolis.toolchain.converter.Main.main(Main.java:34)
Caused by: javax.xml.transform.TransformerException: java.io.FileNotFoundException: g:\JavaModules\converterOutput.xml (A rendszer nem találja a megadott elérési utat)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(Unknown Source)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source)
        at codemetropolis.toolchain.commons.cdf.CdfTree.writeToFile(CdfTree.java:89)
        ... 2 more
Caused by: java.io.FileNotFoundException: g:\JavaModules\converterOutput.xml (A rendszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        ... 5 more

**Comment by brita-sed** [comment]
Instead of exception I got a user friendly message: Error: An error has occurred while converting to CDF format. For more information please check the log file.
