### ISSUE TITLE
Mapping tool, invalid type definition in input file, exception instead of user-friendly error message

### ISSUE THREAD

**Issue by brita-sed** [geryxyz/CodeMetropolis#70]
**Test ID:** MAP-016
**Test name:** Run Mapping Tool with invalid type definition in input, and with valid mapping file
**Precondition:** The input has been generated by the Converter Tool. 
**Steps:**
1. Open the converterOutput.xml
2. Rewrite a line like the following: 
	`<property name=""LOC"" type=""int"" value=""16""/>`  to  `<property name=""LOC"" type=""int"" value=""test""/>`
3. Save the xml. 
4. Open a command line. 
5. Run Mapping Tool with the changed input, valid mapping file, for example: java -jar codemetropolis-toolchain-mapping-1.3.jar -i Modules\converterOutput.xml -m mapping.xml
**Expected Result**: The tool will display an error message: Error: Incorrect type definition in input file. 

**Result:**
Mapping: Reading map file...
Mapping: Reading map file done.
Mapping: Reading graph file...
Exception in thread "main" java.lang.NumberFormatException: For input string: "test"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at java.lang.Double.valueOf(Unknown Source)
        at codemetropolis.toolchain.mapping.control.MappingController.createAttributeMap(MappingController.java:191)
        at codemetropolis.toolchain.mapping.control.MappingController.setAttributes(MappingController.java:146)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:134)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:135)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:135)
        at codemetropolis.toolchain.mapping.control.MappingController.createBuildablesFromCdf(MappingController.java:61)
        at codemetropolis.toolchain.mapping.MappingExecutor.execute(MappingExecutor.java:34)
        at codemetropolis.toolchain.mapping.Main.main(Main.java:32)

**Comment by brita-sed** [comment]
I got an exception again:
Mapping: Reading map file...
Mapping: Reading map file done.
Mapping: Reading graph file...
Exception in thread "main" java.lang.NumberFormatException: For input string: "t
eszt"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at java.lang.Double.valueOf(Unknown Source)
        at codemetropolis.toolchain.mapping.control.MappingController.createAttributeMap(MappingController.java:195)
        at codemetropolis.toolchain.mapping.control.MappingController.setAttributes(MappingController.java:150)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:138)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:139)
        at codemetropolis.toolchain.mapping.control.MappingController.setChildren(MappingController.java:139)
        at codemetropolis.toolchain.mapping.control.MappingController.createBuildablesFromCdf(MappingController.java:66)
        at codemetropolis.toolchain.mapping.MappingExecutor.execute(MappingExecutor.java:42)
        at codemetropolis.toolchain.mapping.Main.main(Main.java:36)

**Comment by brita-sed** [comment]
[converterOutput.zip](https://github.com/geryxyz/CodeMetropolis/files/147971/converterOutput.zip)

**Comment by brita-sed** [comment]
I got a correct, user friendly message now: 
Error: An error has occurred while processing CDF. For more information please check the log file.
